import "./globals.css";

export const metadata = {
  title: "ViaCerta Abroad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-lt-installed="true">
      <head>
        {/* Add favicon */}
        <link rel="icon" href="/viacertaLogo-white.png" />
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
