export const domains = [
    "MBA",
    "Management",
    "Data Science",
    "Engineering",
    "Medicine",
    "Law",
    "Finance",
    "Artificial Intelligence",
    "Cybersecurity",
    "Marketing",
    "Psychology",
    "Education",
    "Hospitality",
    "Architecture",
    "Design",
    "Digital Marketing",
    "Healthcare Management",
    "Business Analytics",
    "Nursing",
    "Accounting",
    "Project Management",
    "Biotechnology",
    "Information Technology",
    "Public Health",
    "Pharmacy",
    "Social Work",
    "Teaching",
    "Hotel Management",
    "History",
  ];

  