const countries = [
  { name: "Russia", flag: "https://flagpedia.net/data/flags/h80/ru.png", image: 'https://swisimmigration.com/assets/images/drop-menu-img/study-in-russia.jpg'},
  { name: "Kazakhstan", flag: "https://flagpedia.net/data/flags/h80/kz.png", image:'https://scontent.fndc2-1.fna.fbcdn.net/v/t39.30808-6/474007563_924163009890953_2343958098230551594_n.jpg?stp=dst-jpg_s960x960_tt6&_nc_cat=110&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=ihSmvYJxh28Q7kNvgFwr_g6&_nc_oc=AdinqCwYYBCYDwK6vSP3H6OQgBzofA0F5XyClCTQX2oIvSALOjj6SB60SmQNry5QN9N_0mYwYxIQZ8_ZcS4xo22F&_nc_zt=23&_nc_ht=scontent.fndc2-1.fna&_nc_gid=AsZ5PNQ2gxwBFywLuUjQeyG&oh=00_AYH4MgFYqe00BYoBApKCLS96f3x4FxukLBhMa0Xcb9j8dQ&oe=67D8651E' },
  { name: "Kyrgyzstan", flag: "https://flagpedia.net/data/flags/h80/kg.png", image: 'https://www.cidentify.com/assets/img/blog-study-in-kyrgyzstan.png' },
  { name: "Philippines", flag: "https://flagpedia.net/data/flags/h80/ph.png", image: 'https://eduniabroad.com/wp-content/uploads/2023/01/STUDY-MBBS-IN-PHILIPPINES.jpg'},
  { name: "Uzbekistan", flag: "https://flagpedia.net/data/flags/h80/uz.png", image: 'https://mediplor.com/wp-content/uploads/2023/06/Mediplor-Banner-Uzbekistan.webp' },
  { name: "Georgia", flag: "https://flagpedia.net/data/flags/h80/ge.png", image: 'https://www.jeduka.com/storage/newsletter/1610457008_Study%20in%20Georgia.jpg'},
  { name: "UK", flag: "https://flagpedia.net/data/flags/h80/gb.png" },
  { name: "USA", flag: "https://flagpedia.net/data/flags/h80/us.png" },
  { name: "Spain", flag: "https://flagpedia.net/data/flags/h80/es.png" },
  { name: "France", flag: "https://flagpedia.net/data/flags/h80/fr.png" },
  { name: "Germany", flag: "https://flagpedia.net/data/flags/h80/de.png" },
  { name: "Poland", flag: "https://flagpedia.net/data/flags/h80/pl.png" },
  { name: "Hungary", flag: "https://flagpedia.net/data/flags/h80/hu.png" },
  { name: "Netherlands", flag: "https://flagpedia.net/data/flags/h80/nl.png" },
  { name: "Belgium", flag: "https://flagpedia.net/data/flags/h80/be.png" },
  { name: "Ireland", flag: "https://flagpedia.net/data/flags/h80/ie.png" },
  { name: "Australia", flag: "https://flagpedia.net/data/flags/h80/au.png" },
  { name: "New Zealand", flag: "https://flagpedia.net/data/flags/h80/nz.png" },
  { name: "Finland", flag: "https://flagpedia.net/data/flags/h80/fi.png" },
  { name: "Sweden", flag: "https://flagpedia.net/data/flags/h80/se.png" },
  { name: "Denmark", flag: "https://flagpedia.net/data/flags/h80/dk.png" },
  { name: "Singapore", flag: "https://flagpedia.net/data/flags/h80/sg.png" },
  { name: "Dubai", flag: "https://flagpedia.net/data/flags/h80/ae.png" },
  { name: "Greece", flag: "https://flagpedia.net/data/flags/h80/gr.png" },
  { name: "Czech Republic", flag: "https://flagpedia.net/data/flags/h80/cz.png" },
  { name: "Canada", flag: "https://flagpedia.net/data/flags/h80/ca.png" }
];

export default countries;
